### ISSUE TITLE
CKZ feature checklist

### ISSUE THREAD

**Issue by zer0k-z** [KZGlobalTeam/cs2kz-metamod#70]
- [x] Slopefix
- [x] Revert network quantization's effect on vertical velocity for consistent height jumps
- [x] ~~Reset prestrafe variables upon teleporting~~ not needed
- [x] Fix player being stuck in water
